### ISSUE TITLE
Add a set_file method

### ISSUE THREAD

**Issue by spencertweed** [matham/ffpyplayer#112]
Just started using Ffpyplayer in my PyQt app on Windows and loving it! One feature request, however, is that you remove filepath from the init method of the MediaPlayer and add it as a separate method. The reason being I have a video player in my app that reacts to what video the user clicks on, and right now I have to destroy the MediaPlayer class and instantiate a new one every time, which can be a bit consuming. It would be great if I could just point it to a new path and not have to re-construct it each time.

If there's a better way to do this already I'd love to hear it, but I couldn't find a solution in the docs.

- Spencer

**Comment by matham** [comment]
The way ffpyplayer is structured, I can't really implement this because the time it takes it make a new player is because it takes time for ffmpeg to setup the threads and read the file and do initial decoding. So I'm afraid there's no easy way to do what you want and make startup faster.

The best I can suggest is to pre-load the videos in a paused state so you can just start playing them when the user clicks on it.
