### ISSUE TITLE
Error installing ffpyplayer on Fedora 24

### ISSUE THREAD

**Issue by GreyGnome** [matham/ffpyplayer#14]
I have tried to install ffpyplayer in two ways and they both fail. I am attempting to install on Fedora 24.

pip install ffpyplayer
pip install https://github.com/matham/ffpyplayer/archive/master.zip

The first fails thus:
Collecting ffpyplayer
  Using cached ffpyplayer-4.0.0.zip
    Complete output from command python setup.py egg_info:
    Selecting SDL2 out of (SDL, SDL2)
    Generating ffconfig.h
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hYVJHt/ffpyplayer/setup.py", line 220, in <module>
        with open(join('ffpyplayer', 'includes', 'ffconfig.h'), 'w') as f:
    IOError: [Errno 2] No such file or directory: 'ffpyplayer/includes/ffconfig.h'

The second failure is included in the attached errorout file.
[errorout.txt](https://github.com/matham/ffpyplayer/files/560555/errorout.txt)

I have the following on my machine:
SDL2_ttf-2.0.14-1.fc24.x86_64
SDL2-devel-2.0.4-8.fc24.x86_64
SDL2_image-devel-2.0.1-2.fc24.x86_64
SDL2_mixer-devel-2.0.1-2.fc24.x86_64
SDL2_image-2.0.1-2.fc24.x86_64
SDL2-2.0.4-8.fc24.x86_64
SDL2_ttf-devel-2.0.14-1.fc24.x86_64
SDL2_mixer-2.0.1-2.fc24.x86_64

There are a number of files in /usr/lib64/pkgconfig that belong to the ffmpeg-devel package:
# rpm -ql ffmpeg-devel-3.0.3-2.fc24.x86_64 | grep pkgconfig

/usr/lib64/pkgconfig/libavcodec.pc
/usr/lib64/pkgconfig/libavdevice.pc
/usr/lib64/pkgconfig/libavfilter.pc
/usr/lib64/pkgconfig/libavformat.pc
/usr/lib64/pkgconfig/libavresample.pc
/usr/lib64/pkgconfig/libavutil.pc
/usr/lib64/pkgconfig/libpostproc.pc
/usr/lib64/pkgconfig/libswresample.pc
/usr/lib64/pkgconfig/libswscale.pc

Thanks.

**Comment by matham** [comment]
I'm not sure why the first one is failing.

For the second one, I think you need to disable warnings being treated as errors. This was supposed to occur here: https://github.com/matham/ffpyplayer/blob/master/setup.py#L209 but I'm not sure why it's not taking effect (I thought the last one wins?, since you do have `-Werror=format-security` on earlier it seems). I guess the real solution would be to fix the printf that generates this error.

Also, as per https://matham.github.io/ffpyplayer/installation.html#ubuntu these ffmpeg binaries (libavcodec etc) need to be compiled as shared, not static. Ubuntu doesn't provide them as shared, does fedora?

**Comment by tmiller02** [comment]
I also encountered the first issue when installing on OS X. It looks like there isn't a 'ffpyplayer/includes' directory in the zip on pypi, but setup.py attempts to write to files expecting this directory to exist. I was able to get the install to work by adding a check in the setup.py script - https://github.com/matham/ffpyplayer/pull/17
