### ISSUE TITLE
CPU hogging when loading images

### ISSUE THREAD

**Issue by ketoni** [matham/ffpyplayer#31]
Building a simple media browser using MediaPlayer, I noticed this when loading images (e.g. jpg, png). No issues with other media formats. I remember installing ffpyplayer using pip for python3.

After calling get_frame() once, some of the created threads started hogging the CPU way too much. Only cure for this was to close the player using close_player(). I couldn't debug well enough to find the root of this issue nor find anything helpful in the documentation to solve this.

Running this in the python3 interpreter, I can reproduce the issue easily
```
> from ffpyplayer.player import MediaPlayer
> player = MediaPlayer("test.jpg")
> player.get_frame()
```
Immidiately after this, CPU usage goes high. This happens with any python script, too.

Could this be a ffmpeg/build -related issue? Or have I missed something relevant regarding image loading? I can attach any additional information to help solve this issue.
Thanks!

**Comment by matham** [comment]
How long does this CPU hogging last? Meaning, if you don't close it, will
it forever hog the CPU? It sounds like a bug in ffpyplayer in that case.

So this happened with many images?


On Oct 4, 2017 4:26 PM, "Juhana Kekoni" <notifications@github.com> wrote:

Building a simple media browser using MediaPlayer, I noticed this when
loading images (e.g. jpg, png). No issues with other media formats. I
remember installing ffpyplayer using pip for python3.
After calling get_frame() once, some of the created threads started hogging
the CPU way too much. Only cure for this was to close the player using
close_player(). I couldn't debug well enough to find the root of this issue
nor find anything helpful in the documentation to solve this.

Running this in the python3 interpreter, I can reproduce the issue easily

> from ffpyplayer.player import MediaPlayer
> player = MediaPlayer("test.jpg")
> player.get_frame()

Immidiately after this, CPU usage goes high. This happens with any python
script, too.

Could this be a ffmpeg/build -related issue? Or have I missed something
relevant regarding image loading?
I can attach any additional information to help solve this issue
Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/matham/ffpyplayer/issues/31>, or mute the thread

**Comment by ketoni** [comment]
I tried again with some test images from here: [https://homepages.cae.wisc.edu/~ece533/images/](url)
And yes, with all of them the hogging seems to go on forever after calling `get_frame()` and it wont stop if you don't `close_player()` or destroy it with `player = None` for example.

Here's a view from htop, which shows that some of the python3 processes have been utilizing the CPU for several minutes, and the CPU% stays about at these values:

```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
31655 keksi      20   0 22504  3948  3368 S  0.0  0.1  0:00.00 ├─ bash
31837 keksi      20   0  415M 39628 20732 S 125.  0.5 13:26.49 │  └─ python3
31859 keksi      20   0  415M 39628 20732 S  0.0  0.5  0:00.00 │     ├─ python3 
31858 keksi      20   0  415M 39628 20732 S  0.0  0.5  0:00.00 │     ├─ python3 
31857 keksi      20   0  415M 39628 20732 S  0.0  0.5  0:00.00 │     ├─ python3 
31856 keksi      20   0  415M 39628 20732 S  0.0  0.5  0:00.00 │     ├─ python3 
31855 keksi      20   0  415M 39628 20732 S  0.0  0.5  0:00.00 │     ├─ python3 
31854 keksi      20   0  415M 39628 20732 R 52.5  0.5  5:38.02 │     ├─ python3 
31853 keksi      20   0  415M 39628 20732 R 72.5  0.5  7:48.25 │     └─ python3 
```
The player won't have any issues with videos, the utilization is negligible with them.

**Comment by matham** [comment]
Oh, I didn't process that you were using media player. For images you're supposed to use `ImageLoader` (https://matham.github.io/ffpyplayer/pic.html#ffpyplayer.pic.ImageLoader). I never really tried to use `MediaPlayer` for images and  wouldn't expect it to work for them.

**Comment by ketoni** [comment]
Ah! So I did miss something relevant, then. 
While it seems that `MediaPlayer` can load images, I worked around the busylooping problem by closing the player immidiately after reading. I'm going to switch to `ImageLoader` now though - should've read the docs more carefully :)

Thanks for the help.
