### ISSUE TITLE
Memory from copied images not freed

### ISSUE THREAD

**Issue by nixnodes** [matham/ffpyplayer#32]
I was (erroneously) using memoryview instead of to_bytearray to pass data to a cairo ImageSurface object and had to do a deepcopy on the image each frame, otherwise the original buffer contents would change by the time it got rendered. 

Doing copy.deepcopy(img) around 30 times per second caused a massive memory leak, even if no references to the image were kept. 

Have I missed something, does the image object need to be released manually? I've tried deleting immediatelly after a copy, no effect. 

Using python3 and ffyplayer 4.1.0 @d1b43f6

**Comment by matham** [comment]
Yes, this is a bug. There should have been a `av_frame_free(&frame)` after this line: https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/pic.pyx#L469 because it is cloned in that line. Can you try and submit a pr if it fixes it?

Also, there's no reason that the original buffer would get overwritten by the time you render as long as you still maintain a ref to the image. The only way I can see memoryview buffers being overwritten is if you make a memoryview and then release all references to the image (but that may give seg faults) before cairo fully rendered it. Could this be the case?

**Comment by nixnodes** [comment]
That fixed it, PR submitted.

You are correct, I neglected to notice that rather large and obvious warning in the docs, under 'to_memoryview'. The symptoms were picture glitches, suprisingly it never caused a crash. After ensuring the reference is kept until the renderer does it's job, the problem went away (no need to copy anything).
