### ISSUE TITLE
Support ffmpeg's per-file options

### ISSUE THREAD

**Issue by tigarmo** [matham/ffpyplayer#7]
Hi,

I've been experimenting with your library (very nice work by the way) and I'm wondering if there's a special syntax that I need to use with `lib_opts` to support ffmpeg's per-file options. Specifically, I'm trying to use the `qscale` flag, which as I understand is the 'preferred' way of setting the output video quality:

```
-q q                use fixed quality scale (VBR)
-qscale q           use fixed quality scale (VBR)
```

From the docs, `lib_opts` is meant to receive flags that the encoder supports, and it looks `qscale` isn't one of them for the codec I was experimenting with (`msmpeg4v2`). I was eventually able to find [this](http://www.manpagez.com/man/1/ffmpeg-codecs/) page, which made me try `lib_opts={'flags':'qscale'}` which for my case worked - the output video has visibly higher quality, even if I couldn't set the specific number to `qscale`.

My question is, is there a way to pass these "general" per-file options that ffmpeg (the binary) supports? If the answer is "no", is there an interest in such functionality?

Thank you for your time.

**Comment by matham** [comment]
Try setting `global_quality`, e.g. `'global_quality': '55'`. It needs to be an int rather than a float. It comes from https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/options_table.h#L325. Remember to still set `'flags': 'qscale'`.

The issue is that the `qscale` you're setting for the ffmpeg binary is a higher level option specific to that binary and is not an externally available declared option for the ffmpeg library API. So this option is not available. In particular ffpyplayer is based on ffplay which lacked this high level option.

That link should tell you some of the options that are available. FFmpeg is not a particularly user friendly library so it's sometimes hard to find the option you need. But if you trace it down, you'll see that the `qscale` you set in ffmpeg gets translated to `global_quality` at https://github.com/FFmpeg/FFmpeg/blob/b975aeec02e4518a4e5f2996cf51d113e42e1727/ffmpeg_opt.c#L1307 and then can be overwritten for each stream at https://github.com/FFmpeg/FFmpeg/blob/b975aeec02e4518a4e5f2996cf51d113e42e1727/ffmpeg_opt.c#L1524.

However, it seems only `global_quality` is available as a option and the per stream settings of qscale ithat may override it is not available. Of course we can always modify the code to directly set the qscale override for each stream, but ffmpeg doesn't seem to provide a generic way to do that.

Let me know if that help.

**Comment by tigarmo** [comment]
Thank you, that's very helpful. I'm experimenting with `global_quality` here now but so far the value I set seems to make no difference. I'll keep trying though, your links are very useful.

Thanks again, I'll go ahead and close the issue.
