### ISSUE TITLE
On Linux, can't import any modules from ffpyplayer

### ISSUE THREAD

**Issue by muizzsiddique** [matham/ffpyplayer#97]
I'm running Linux Mint Debian Edition and followed the install guide here (http://matham.github.io/ffpyplayer/installation.html) under **SDL and Compiling FFmpeg >> Linux >> Ubuntu 18.04** and everything installed fine. However, importing any of the modules inside ffpyplayer gives this same error:

`Traceback (most recent call last):`
`  File "verysimpleplayer.py", line 1, in <module>`
`    import wx, ffpyplayer.player as ffplay`
`  File "/home/muizz/.local/lib/python3.7/site-packages/ffpyplayer/player/__init__.py", line 10, in <module>`
`    from ffpyplayer.player.player import MediaPlayer`
`  File "ffpyplayer/player/player.pyx", line 2, in init ffpyplayer.player.player`
`  File "ffpyplayer/player/frame_queue.pyx", line 2, in init ffpyplayer.player.frame_queue`
`  File "ffpyplayer/player/decoder.pyx", line 2, in init ffpyplayer.player.decoder`
`  File "ffpyplayer/pic.pyx", line 70, in init ffpyplayer.pic`
`  File "ffpyplayer/tools.pyx", line 84, in init ffpyplayer.tools`
`NameError: name 'get_codecs' is not defined`

**Comment by matham** [comment]
Something must be wrong with your setup as it works on the CI and it works for me on windows. I'd say make sure you're not in the ffpyplayer directory but that you installed it using pip and cd'd to e.g. home and try again. Sometimes if you're in the source directory python could get confused trying to load the source rather than the install package.
